In [1]:
import pandas as pd

chess = {
    'Name': ['Magnus Carlsen', 'Ziaur Rahman', 'Hikaru Nakamura', 'Ian Nepomniachtchi', 'Fabiano Caruana', 
             'Ding Liren', 'Alireza Firouzja', 'Wesley So', 'Anish Giri', 'Vishwanathan Anand'],
    'Country': ['Norway', 'Bangladesh', 'USA', 'Russia', 'USA', 
                'China', 'France', 'USA', 'Netherlands', 'India'],
    'Rating': [2832, 2300, 2802, 2793, 2782, 
               2781, 2778, 2769, 2768, 2754],
    'DOB': ['1990-11-30', '1974-09-22', '1987-12-09', '1990-07-14', '1992-07-30', 
            '1992-10-24', '2003-06-18', '1993-10-09', '1994-06-28', '1969-12-11'],
    'World Rank': [1, None, 2, 3, 4, 5, 6, 7, 8, 9],
    'Peak Rating': [2882, 2524, 2900, 2799, 2844, 
                    2816, 2816, 2822, 2798, 2817],
    'Titles': ['GM', 'GM', 'GM', 'GM', 'GM', 
               'GM', 'GM', 'GM', 'GM', 'GM'],
    'Active': [True, True, True, True, True, 
               True, True, True, True, True]
}

newdf = pd.DataFrame(chess)

newdf

,Name,Country,Rating,DOB,World Rank,Peak Rating,Titles,Active
0,Magnus Carlsen,Norway,2832,1990-11-30,1.0,2882,GM,True
1,Ziaur Rahman,Bangladesh,2300,1974-09-22,NaN,2524,GM,True
2,Hikaru Nakamura,USA,2802,1987-12-09,2.0,2900,GM,True
3,Ian Nepomniachtchi,Russia,2793,1990-07-14,3.0,2799,GM,True
4,Fabiano Caruana,USA,2782,1992-07-30,4.0,2844,GM,True
5,Ding Liren,China,2781,1992-10-24,5.0,2816,GM,True
6,Alireza Firouzja,France,2778,2003-06-18,6.0,2816,GM,True
7,Wesley So,USA,2769,1993-10-09,7.0,2822,GM,True
8,Anish Giri,Netherlands,2768,1994-06-28,8.0,2798,GM,True
9,Vishwanathan Anand,India,2754,1969-12-11,9.0,2817,GM,True

In [2]:
filt=(newdf['Country']=='USA')

In [3]:
newdf[filt]

,Name,Country,Rating,DOB,World Rank,Peak Rating,Titles,Active
2,Hikaru Nakamura,USA,2802,1987-12-09,2.0,2900,GM,True
4,Fabiano Caruana,USA,2782,1992-07-30,4.0,2844,GM,True
7,Wesley So,USA,2769,1993-10-09,7.0,2822,GM,True

In [4]:
newdf['Rating'] = newdf['Rating'].astype(int)

def update_rating(Rating):
    return Rating + 5

filt = (newdf['Country'] == 'USA')

newdf.loc[filt, 'Rating'] = newdf.loc[filt, 'Rating'].apply(update_rating)

print(newdf)
newdf

                 Name      Country  Rating         DOB  World Rank  \
0      Magnus Carlsen       Norway    2832  1990-11-30         1.0
1        Ziaur Rahman   Bangladesh    2300  1974-09-22         NaN
2     Hikaru Nakamura          USA    2807  1987-12-09         2.0
3  Ian Nepomniachtchi       Russia    2793  1990-07-14         3.0
4     Fabiano Caruana          USA    2787  1992-07-30         4.0
5          Ding Liren        China    2781  1992-10-24         5.0
6    Alireza Firouzja       France    2778  2003-06-18         6.0
7           Wesley So          USA    2774  1993-10-09         7.0
8          Anish Giri  Netherlands    2768  1994-06-28         8.0
9  Vishwanathan Anand        India    2754  1969-12-11         9.0

   Peak Rating Titles  Active
0         2882     GM    True
1         2524     GM    True
2         2900     GM    True
3         2799     GM    True
4         2844     GM    True
5         2816     GM    True
6         2816     GM    True
7         2822     GM    True
8         2798     GM    True
9         2817     GM    True

,Name,Country,Rating,DOB,World Rank,Peak Rating,Titles,Active
0,Magnus Carlsen,Norway,2832,1990-11-30,1.0,2882,GM,True
1,Ziaur Rahman,Bangladesh,2300,1974-09-22,NaN,2524,GM,True
2,Hikaru Nakamura,USA,2807,1987-12-09,2.0,2900,GM,True
3,Ian Nepomniachtchi,Russia,2793,1990-07-14,3.0,2799,GM,True
4,Fabiano Caruana,USA,2787,1992-07-30,4.0,2844,GM,True
5,Ding Liren,China,2781,1992-10-24,5.0,2816,GM,True
6,Alireza Firouzja,France,2778,2003-06-18,6.0,2816,GM,True
7,Wesley So,USA,2774,1993-10-09,7.0,2822,GM,True
8,Anish Giri,Netherlands,2768,1994-06-28,8.0,2798,GM,True
9,Vishwanathan Anand,India,2754,1969-12-11,9.0,2817,GM,True