In [3]:
import pandas as pd
df_normalized=pd.read_csv("data/prediction_nusselt_normalized.csv")

In [29]:
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

X = df_normalized[['x1', 'x2', 'x3', 'x4', 'x5']].values  
y = df_normalized['nu'].values.reshape(-1, 1) 

degree = 3  
poly = PolynomialFeatures(degree)
X_poly = poly.fit_transform(X)

reg = linear_model.LinearRegression()
reg.fit(X_poly, y)

m_reg = reg.coef_
c_reg = reg.intercept_[0]

print('Polynomial Regression Coefficients:')
for i, coef in enumerate(m_reg[0], start=0):  
    print(f'Coefficient for feature {i} = {coef:<3.2f}')
print(f'Intercept(c) = {c_reg:3.2f}')

y_pred = reg.predict(X_poly)

Polynomial Regression Coefficients:
Coefficient for feature 0 = 9159191085.14
Coefficient for feature 1 = -2326250594768.20
Coefficient for feature 2 = -5377911644315.34
Coefficient for feature 3 = 12176307780.05
Coefficient for feature 4 = 74518725767.76
Coefficient for feature 5 = -513539362348.43
Coefficient for feature 6 = -4160615690563.40
Coefficient for feature 7 = 1941908092383.57
Coefficient for feature 8 = -727017248311.16
Coefficient for feature 9 = 374207362379.82
Coefficient for feature 10 = 527058012718.42
Coefficient for feature 11 = -1628510355545.22
Coefficient for feature 12 = -686843878700.49
Coefficient for feature 13 = 137984838425.29
Coefficient for feature 14 = -4.16
Coefficient for feature 15 = -1359832193133.78
Coefficient for feature 16 = -2023881562129.94
Coefficient for feature 17 = 126435174024.68
Coefficient for feature 18 = 2575727147347.76
Coefficient for feature 19 = -103566640108.54
Coefficient for feature 20 = -1.73
Coefficient for feature 21 = 229995766084.64
Coefficient for feature 22 = 346206497617.72
Coefficient for feature 23 = 244048622433.38
Coefficient for feature 24 = -1138589260673.48
Coefficient for feature 25 = 557785770982.75
Coefficient for feature 26 = -1111705861443.39
Coefficient for feature 27 = 1088200271506.15
Coefficient for feature 28 = -217298918068.63
Coefficient for feature 29 = -1.04
Coefficient for feature 30 = 2405226073075.09
Coefficient for feature 31 = 0.15
Coefficient for feature 32 = 1.09
Coefficient for feature 33 = -1760074287670.05
Coefficient for feature 34 = -0.91
Coefficient for feature 35 = -0.09
Coefficient for feature 36 = 3474013916010.91
Coefficient for feature 37 = -2.12
Coefficient for feature 38 = -0.02
Coefficient for feature 39 = -9.03
Coefficient for feature 40 = 1588478530.87
Coefficient for feature 41 = -2.20
Coefficient for feature 42 = -6.63
Coefficient for feature 43 = -1162402257.15
Coefficient for feature 44 = 3.28
Coefficient for feature 45 = -0.26
Coefficient for feature 46 = 235589919478.69
Coefficient for feature 47 = 2123581512825.44
Coefficient for feature 48 = -149641047353.12
Coefficient for feature 49 = 242779993404.93
Coefficient for feature 50 = -3.04
Coefficient for feature 51 = -0.45
Coefficient for feature 52 = -2041799369591.13
Coefficient for feature 53 = 109502953917.02
Coefficient for feature 54 = 0.26
Coefficient for feature 55 = 4.24
Intercept(c) = 4598829154937.60

In [10]:
df_normalized.rename(columns={'y_pred':'nu_pred(LinearReg)'},inplace=True)

In [12]:
df_normalized

,x1,x2,x3,x4,x5,nu,nu_pred(LinearReg)
0,0.629941,-0.987511,-1.524983,-1.717719,-1.482433,24.058300,32.718774
1,0.629941,-0.987511,-1.524983,-1.717719,-0.889460,40.439094,42.875931
2,0.629941,-0.987511,-1.524983,-1.717719,-0.296487,50.367336,53.033088
3,0.629941,-0.987511,-1.524983,-1.717719,0.296487,60.316725,63.190245
4,0.629941,-0.987511,-1.524983,-1.717719,0.889460,70.229644,73.347401
...,...,...,...,...,...,...,...
121,-1.574852,1.283043,-1.524983,-1.717719,-0.889460,43.419611,43.694315
122,-1.574852,1.283043,-1.524983,-1.717719,-0.296487,54.123641,53.851472
123,-1.574852,1.283043,-1.524983,-1.717719,0.296487,64.855564,64.008628
124,-1.574852,1.283043,-1.524983,-1.717719,0.889460,75.998030,74.165785
125,-1.574852,1.283043,-1.524983,-1.717719,1.482433,87.884082,84.322942

In [ ]:
df_normalized

In [14]:
m1, m2, m3, m4, m5 = -1.14, -0.74, 3.10, -1.89, 17.13
c = 59.56

df_normalized['nu_pred(gradient)'] = (
    c + 
    m1 * df_normalized['x1'] + 
    m2 * df_normalized['x2'] + 
    m3 * df_normalized['x3'] + 
    m4 * df_normalized['x4'] + 
    m5 * df_normalized['x5']
)

df_normalized.head()

,x1,x2,x3,x4,x5,nu,nu_pred(LinearReg),nu_pred(gradient)
0,0.629941,-0.987511,-1.524983,-1.717719,-1.482433,24.058300,32.718774,32.697581
1,0.629941,-0.987511,-1.524983,-1.717719,-0.889460,40.439094,42.875931,42.855215
2,0.629941,-0.987511,-1.524983,-1.717719,-0.296487,50.367336,53.033088,53.012850
3,0.629941,-0.987511,-1.524983,-1.717719,0.296487,60.316725,63.190245,63.170484
4,0.629941,-0.987511,-1.524983,-1.717719,0.889460,70.229644,73.347401,73.328118

In [16]:
pd.set_option('display.max_rows',126)

In [17]:
df_normalized

,x1,x2,x3,x4,x5,nu,nu_pred(LinearReg),nu_pred(gradient)
0,0.629941,-0.987511,-1.524983,-1.717719,-1.482433,24.058300,32.718774,32.697581
1,0.629941,-0.987511,-1.524983,-1.717719,-0.889460,40.439094,42.875931,42.855215
2,0.629941,-0.987511,-1.524983,-1.717719,-0.296487,50.367336,53.033088,53.012850
3,0.629941,-0.987511,-1.524983,-1.717719,0.296487,60.316725,63.190245,63.170484
4,0.629941,-0.987511,-1.524983,-1.717719,0.889460,70.229644,73.347401,73.328118
5,0.629941,-0.987511,-1.524983,-1.717719,1.482433,83.020652,83.504558,83.485752
6,0.629941,-0.987511,-0.226687,0.911017,-1.482433,24.555150,31.677056,31.753989
7,0.629941,-0.987511,-0.226687,0.911017,-0.889460,41.639580,41.834213,41.911623
8,0.629941,-0.987511,-0.226687,0.911017,-0.296487,53.141126,51.991370,52.069258
9,0.629941,-0.987511,-0.226687,0.911017,0.296487,64.252202,62.148526,62.226892
10,0.629941,-0.987511,-0.226687,0.911017,0.889460,75.108814,72.305683,72.384526
11,0.629941,-0.987511,-0.226687,0.911017,1.482433,87.650420,82.462840,82.542160
12,0.629941,-0.987511,1.071610,0.911017,-1.482433,25.293990,35.804058,35.778708
13,0.629941,-0.987511,1.071610,0.911017,-0.889460,42.871722,45.961215,45.936342
14,0.629941,-0.987511,1.071610,0.911017,-0.296487,54.531179,56.118372,56.093977
15,0.629941,-0.987511,1.071610,0.911017,0.296487,65.700271,66.275529,66.251611
16,0.629941,-0.987511,1.071610,0.911017,0.889460,76.412691,76.432685,76.409245
17,0.629941,-0.987511,1.071610,0.911017,1.482433,88.693748,86.589842,86.566879
18,0.629941,-0.987511,-0.226687,0.034772,-1.482433,26.221770,33.399963,33.410093
19,0.629941,-0.987511,-0.226687,0.034772,-0.889460,44.357110,43.557120,43.567727
20,0.629941,-0.987511,-0.226687,0.034772,-0.296487,56.704718,53.714277,53.725361
21,0.629941,-0.987511,-0.226687,0.034772,0.296487,68.308351,63.871433,63.882996
22,0.629941,-0.987511,-0.226687,0.034772,0.889460,79.089554,74.028590,74.040630
23,0.629941,-0.987511,-0.226687,0.034772,1.482433,92.253018,84.185747,84.198264
24,0.629941,-0.987511,1.071610,0.034772,-1.482433,26.553120,37.526965,37.434812
25,0.629941,-0.987511,1.071610,0.034772,-0.889460,45.357921,47.684122,47.592446
26,0.629941,-0.987511,1.071610,0.034772,-0.296487,58.015792,57.841279,57.750080
27,0.629941,-0.987511,1.071610,0.034772,0.296487,69.768098,67.998435,67.907714
28,0.629941,-0.987511,1.071610,0.034772,0.889460,81.466940,78.155592,78.065349
29,0.629941,-0.987511,1.071610,0.034772,1.482433,95.540588,88.312749,88.222983
30,0.629941,1.283043,-1.524983,-1.717719,-1.482433,24.268920,31.032271,31.017371
31,0.629941,1.283043,-1.524983,-1.717719,-0.889460,40.814093,41.189428,41.175005
32,0.629941,1.283043,-1.524983,-1.717719,-0.296487,50.875970,51.346585,51.332640
33,0.629941,1.283043,-1.524983,-1.717719,0.296487,60.962907,61.503741,61.490274
34,0.629941,1.283043,-1.524983,-1.717719,0.889460,71.436766,71.660898,71.647908
35,0.629941,1.283043,-1.524983,-1.717719,1.482433,82.611302,81.818055,81.805542
36,0.629941,1.283043,-0.226687,0.911017,-1.482433,24.761010,29.990553,30.073779
37,0.629941,1.283043,-0.226687,0.911017,-0.889460,40.675295,40.147709,40.231414
38,0.629941,1.283043,-0.226687,0.911017,-0.296487,50.651666,50.304866,50.389048
39,0.629941,1.283043,-0.226687,0.911017,0.296487,60.651494,60.462023,60.546682
40,0.629941,1.283043,-0.226687,0.911017,0.889460,70.593623,70.619180,70.704316
41,0.629941,1.283043,-0.226687,0.911017,1.482433,83.178239,80.776337,80.861950
42,0.629941,1.283043,1.071610,0.911017,-1.482433,25.491390,34.117555,34.098498
43,0.629941,1.283043,1.071610,0.911017,-0.889460,40.465794,44.274712,44.256132
44,0.629941,1.283043,1.071610,0.911017,-0.296487,51.242438,54.431869,54.413767
45,0.629941,1.283043,1.071610,0.911017,0.296487,62.045065,64.589025,64.571401
46,0.629941,1.283043,1.071610,0.911017,-0.889460,72.362841,44.274712,44.256132
47,0.629941,1.283043,1.071610,0.911017,-0.296487,84.411756,54.431869,54.413767
48,0.629941,1.283043,1.071610,0.911017,0.296487,26.409300,64.589025,64.571401
49,0.629941,1.283043,1.071610,0.911017,0.889460,43.777565,74.746182,74.729035
50,0.629941,1.283043,1.071610,0.911017,1.482433,54.063616,84.903339,84.886669
51,0.629941,1.283043,-0.226687,0.034772,-1.482433,64.384552,31.713460,31.729883
52,0.629941,1.283043,-0.226687,0.034772,-0.889460,74.657295,41.870616,41.887517
53,0.629941,1.283043,-0.226687,0.034772,-0.296487,86.427770,52.027773,52.045151
54,0.629941,1.283043,-0.226687,0.034772,0.296487,27.400530,62.184930,62.202786
55,0.629941,1.283043,-0.226687,0.034772,0.889460,46.597368,72.342087,72.360420
56,0.629941,1.283043,-0.226687,0.034772,1.482433,58.445445,82.499243,82.518054
57,0.629941,1.283043,1.071610,0.034772,-1.482433,70.313070,35.840462,35.754602
58,0.629941,1.283043,1.071610,0.034772,-0.889460,81.692693,45.997618,45.912236
59,0.629941,1.283043,1.071610,0.034772,-0.296487,94.279900,56.154775,56.069870
60,0.629941,1.283043,1.071610,0.034772,0.296487,25.130430,66.311932,66.227505
61,0.629941,1.283043,1.071610,0.034772,0.889460,42.301917,76.469089,76.385139
62,0.629941,0.374822,-1.524983,-1.717719,-0.296487,52.806249,52.021186,52.004724
63,0.629941,0.374822,-1.524983,-1.717719,0.296487,63.341320,62.178343,62.162358
64,0.629941,0.374822,-1.524983,-1.717719,0.889460,74.251849,72.335499,72.319992
65,0.629941,0.374822,-1.524983,-1.717719,1.482433,85.933276,82.492656,82.477626
66,0.629941,0.374822,-0.226687,0.911017,-1.482433,25.622520,30.665154,30.745863
67,0.629941,0.374822,-0.226687,0.911017,-0.889460,42.163110,40.822311,40.903498
68,0.629941,0.374822,-0.226687,0.911017,-0.296487,52.581945,50.979468,51.061132
69,0.629941,0.374822,-0.226687,0.911017,0.296487,63.029908,61.136625,61.218766
70,0.629941,0.374822,-0.226687,0.911017,0.889460,73.400707,71.293781,71.376400
71,0.629941,0.374822,-0.226687,0.911017,1.482433,86.498412,81.450938,81.534034
72,0.629941,0.374822,1.071610,0.911017,-1.482433,26.352900,34.792156,34.770582
73,0.629941,0.374822,1.071610,0.911017,-0.889460,41.953703,44.949313,44.928216
74,0.629941,0.374822,1.071610,0.911017,-0.296487,53.172718,55.106470,55.085851
75,0.629941,0.374822,1.071610,0.911017,0.296487,64.423479,65.263627,65.243485
76,0.629941,0.374822,1.071610,0.911017,0.889460,75.177924,75.420783,75.401119
77,0.629941,0.374822,1.071610,0.911017,1.482433,87.731930,85.577940,85.558753
78,0.629941,0.374822,-0.226687,0.034772,-1.482433,27.270810,32.388061,32.401967
79,0.629941,0.374822,-0.226687,0.034772,-0.889460,45.265389,42.545218,42.559601
80,0.629941,0.374822,-0.226687,0.034772,-0.296487,55.993895,52.702375,52.717235
81,0.629941,0.374822,-0.226687,0.034772,0.296487,66.762966,62.859531,62.874870
82,0.629941,0.374822,-0.226687,0.034772,0.889460,77.472379,73.016688,73.032504
83,0.629941,0.374822,-0.226687,0.034772,1.482433,89.747944,83.173845,83.190138
84,0.629941,0.374822,1.071610,0.034772,-1.482433,28.262040,36.515063,36.426686
85,0.629941,0.374822,1.071610,0.034772,-0.889460,48.095192,46.672220,46.584320
86,0.629941,0.374822,1.071610,0.034772,-0.296487,60.375724,56.829377,56.741954
87,0.629941,0.374822,1.071610,0.034772,0.296487,72.691483,66.986533,66.899588
88,0.629941,0.374822,1.071610,0.034772,0.889460,84.507782,77.143690,77.057223
89,0.629941,0.374822,1.071610,0.034772,1.482433,97.600074,87.300847,87.214857
90,-1.574852,-0.987511,-1.524983,-1.717719,-1.482433,25.325010,35.223661,35.211045
91,-1.574852,-0.987511,-1.524983,-1.717719,-0.889460,42.567339,45.380818,45.368679
92,-1.574852,-0.987511,-1.524983,-1.717719,-0.296487,53.017916,55.537975,55.526313
93,-1.574852,-0.987511,-1.524983,-1.717719,0.296487,63.493134,65.695132,65.683947
94,-1.574852,-0.987511,-1.524983,-1.717719,0.889460,73.924728,75.852288,75.841582
95,-1.574852,-0.987511,-1.524983,-1.717719,1.482433,87.389588,86.009445,85.999216
96,-1.574852,-0.987511,-0.226687,0.911017,-1.482433,25.848120,34.181943,34.267453
97,-1.574852,-0.987511,-0.226687,0.911017,-0.889460,43.831137,44.339100,44.425087
98,-1.574852,-0.987511,-0.226687,0.911017,-0.296487,55.937029,54.496257,54.582722
99,-1.574852,-0.987511,-0.226687,0.911017,0.296487,67.634921,64.653413,64.740356
100,-1.574852,-0.987511,-0.226687,0.911017,0.889460,79.061910,74.810570,74.897990
101,-1.574852,-0.987511,-0.226687,0.911017,1.482433,92.263886,84.967727,85.055624
102,-1.574852,-0.987511,1.071610,0.911017,-1.482433,26.625030,38.308945,38.292172
103,-1.574852,-0.987511,1.071610,0.911017,-0.889460,45.129025,48.466102,48.449806
104,-1.574852,-0.987511,1.071610,0.911017,-0.296487,57.399745,58.623259,58.607441
105,-1.574852,-0.987511,1.071610,0.911017,0.296487,69.156950,68.780416,68.765075
106,-1.574852,-0.987511,1.071610,0.911017,0.889460,80.434962,78.937572,78.922709
107,-1.574852,-0.987511,1.071610,0.911017,1.482433,93.361554,89.094729,89.080343
108,-1.574852,-0.987511,-0.226687,0.034772,-1.482433,27.602160,35.904850,35.923557
109,-1.574852,-0.987511,-0.226687,0.034772,-0.889460,46.692336,46.062007,46.081191
110,-1.574852,-0.987511,-0.226687,0.034772,-0.296487,59.690175,56.219164,56.238825
111,-1.574852,-0.987511,-0.226687,0.034772,0.296487,71.905166,66.376320,66.396459
112,-1.574852,-0.987511,-0.226687,0.034772,0.889460,83.249979,76.533477,76.554093
113,-1.574852,-0.987511,-0.226687,0.034772,1.482433,97.105580,86.690634,86.711727
114,-1.574852,-0.987511,1.071610,0.034772,-1.482433,27.950430,40.031852,39.948276
115,-1.574852,-0.987511,1.071610,0.034772,-0.889460,47.744283,50.189009,50.105910
116,-1.574852,-0.987511,1.071610,0.034772,-0.296487,61.070751,60.346166,60.263544
117,-1.574852,-0.987511,1.071610,0.034772,0.296487,73.438873,70.503322,70.421178
118,-1.574852,-0.987511,1.071610,0.034772,0.889460,85.756371,80.660479,80.578812
119,-1.574852,-0.987511,1.071610,0.034772,1.482433,100.567038,90.817636,90.736446
120,-1.574852,1.283043,-1.524983,-1.717719,-1.482433,25.818510,33.537158,33.530835
121,-1.574852,1.283043,-1.524983,-1.717719,-0.889460,43.419611,43.694315,43.688469
122,-1.574852,1.283043,-1.524983,-1.717719,-0.296487,54.123641,53.851472,53.846103
123,-1.574852,1.283043,-1.524983,-1.717719,0.296487,64.855564,64.008628,64.003738
124,-1.574852,1.283043,-1.524983,-1.717719,0.889460,75.998030,74.165785,74.161372
125,-1.574852,1.283043,-1.524983,-1.717719,1.482433,87.884082,84.322942,84.319006

In [26]:
df_normalized = df_normalized.drop(columns='nu_pred(2nd order)')

In [27]:
y_pred_df = pd.DataFrame(y_pred, columns=['y_pred'])

df_normalized['nu_pred(2nd order)'] = y_pred_df['y_pred']

In [28]:
df_normalized

,x1,x2,x3,x4,x5,nu,nu_pred(LinearReg),nu_pred(gradient),nu_pred(2nd order)
0,0.629941,-0.987511,-1.524983,-1.717719,-1.482433,24.058300,32.718774,32.697581,17.37500
1,0.629941,-0.987511,-1.524983,-1.717719,-0.889460,40.439094,42.875931,42.855215,33.43750
2,0.629941,-0.987511,-1.524983,-1.717719,-0.296487,50.367336,53.033088,53.012850,48.68750
3,0.629941,-0.987511,-1.524983,-1.717719,0.296487,60.316725,63.190245,63.170484,63.12500
4,0.629941,-0.987511,-1.524983,-1.717719,0.889460,70.229644,73.347401,73.328118,76.75000
5,0.629941,-0.987511,-1.524983,-1.717719,1.482433,83.020652,83.504558,83.485752,89.59375
6,0.629941,-0.987511,-0.226687,0.911017,-1.482433,24.555150,31.677056,31.753989,22.40625
7,0.629941,-0.987511,-0.226687,0.911017,-0.889460,41.639580,41.834213,41.911623,37.84375
8,0.629941,-0.987511,-0.226687,0.911017,-0.296487,53.141126,51.991370,52.069258,52.50000
9,0.629941,-0.987511,-0.226687,0.911017,0.296487,64.252202,62.148526,62.226892,66.31250
10,0.629941,-0.987511,-0.226687,0.911017,0.889460,75.108814,72.305683,72.384526,79.31250
11,0.629941,-0.987511,-0.226687,0.911017,1.482433,87.650420,82.462840,82.542160,91.53125
12,0.629941,-0.987511,1.071610,0.911017,-1.482433,25.293990,35.804058,35.778708,26.90625
13,0.629941,-0.987511,1.071610,0.911017,-0.889460,42.871722,45.961215,45.936342,40.34375
14,0.629941,-0.987511,1.071610,0.911017,-0.296487,54.531179,56.118372,56.093977,53.00000
15,0.629941,-0.987511,1.071610,0.911017,0.296487,65.700271,66.275529,66.251611,64.84375
16,0.629941,-0.987511,1.071610,0.911017,0.889460,76.412691,76.432685,76.409245,75.84375
17,0.629941,-0.987511,1.071610,0.911017,1.482433,88.693748,86.589842,86.566879,86.06250
18,0.629941,-0.987511,-0.226687,0.034772,-1.482433,26.221770,33.399963,33.410093,26.40625
19,0.629941,-0.987511,-0.226687,0.034772,-0.889460,44.357110,43.557120,43.567727,41.40625
20,0.629941,-0.987511,-0.226687,0.034772,-0.296487,56.704718,53.714277,53.725361,55.59375
21,0.629941,-0.987511,-0.226687,0.034772,0.296487,68.308351,63.871433,63.882996,68.93750
22,0.629941,-0.987511,-0.226687,0.034772,0.889460,79.089554,74.028590,74.040630,81.50000
23,0.629941,-0.987511,-0.226687,0.034772,1.482433,92.253018,84.185747,84.198264,93.25000
24,0.629941,-0.987511,1.071610,0.034772,-1.482433,26.553120,37.526965,37.434812,34.37500
25,0.629941,-0.987511,1.071610,0.034772,-0.889460,45.357921,47.684122,47.592446,47.37500
26,0.629941,-0.987511,1.071610,0.034772,-0.296487,58.015792,57.841279,57.750080,59.59375
27,0.629941,-0.987511,1.071610,0.034772,0.296487,69.768098,67.998435,67.907714,70.93750
28,0.629941,-0.987511,1.071610,0.034772,0.889460,81.466940,78.155592,78.065349,81.53125
29,0.629941,-0.987511,1.071610,0.034772,1.482433,95.540588,88.312749,88.222983,91.28125
30,0.629941,1.283043,-1.524983,-1.717719,-1.482433,24.268920,31.032271,31.017371,37.93750
31,0.629941,1.283043,-1.524983,-1.717719,-0.889460,40.814093,41.189428,41.175005,46.53125
32,0.629941,1.283043,-1.524983,-1.717719,-0.296487,50.875970,51.346585,51.332640,54.31250
33,0.629941,1.283043,-1.524983,-1.717719,0.296487,60.962907,61.503741,61.490274,61.25000
34,0.629941,1.283043,-1.524983,-1.717719,0.889460,71.436766,71.660898,71.647908,67.37500
35,0.629941,1.283043,-1.524983,-1.717719,1.482433,82.611302,81.818055,81.805542,72.75000
36,0.629941,1.283043,-0.226687,0.911017,-1.482433,24.761010,29.990553,30.073779,36.50000
37,0.629941,1.283043,-0.226687,0.911017,-0.889460,40.675295,40.147709,40.231414,44.46875
38,0.629941,1.283043,-0.226687,0.911017,-0.296487,50.651666,50.304866,50.389048,51.62500
39,0.629941,1.283043,-0.226687,0.911017,0.296487,60.651494,60.462023,60.546682,57.96875
40,0.629941,1.283043,-0.226687,0.911017,0.889460,70.593623,70.619180,70.704316,63.50000
41,0.629941,1.283043,-0.226687,0.911017,1.482433,83.178239,80.776337,80.861950,68.25000
42,0.629941,1.283043,1.071610,0.911017,-1.482433,25.491390,34.117555,34.098498,41.53125
43,0.629941,1.283043,1.071610,0.911017,-0.889460,40.465794,44.274712,44.256132,47.50000
44,0.629941,1.283043,1.071610,0.911017,-0.296487,51.242438,54.431869,54.413767,52.68750
45,0.629941,1.283043,1.071610,0.911017,0.296487,62.045065,64.589025,64.571401,57.03125
46,0.629941,1.283043,1.071610,0.911017,-0.889460,72.362841,44.274712,44.256132,47.50000
47,0.629941,1.283043,1.071610,0.911017,-0.296487,84.411756,54.431869,54.413767,52.68750
48,0.629941,1.283043,1.071610,0.911017,0.296487,26.409300,64.589025,64.571401,57.03125
49,0.629941,1.283043,1.071610,0.911017,0.889460,43.777565,74.746182,74.729035,60.56250
50,0.629941,1.283043,1.071610,0.911017,1.482433,54.063616,84.903339,84.886669,63.31250
51,0.629941,1.283043,-0.226687,0.034772,-1.482433,64.384552,31.713460,31.729883,42.81250
52,0.629941,1.283043,-0.226687,0.034772,-0.889460,74.657295,41.870616,41.887517,50.34375
53,0.629941,1.283043,-0.226687,0.034772,-0.296487,86.427770,52.027773,52.045151,57.03125
54,0.629941,1.283043,-0.226687,0.034772,0.296487,27.400530,62.184930,62.202786,62.93750
55,0.629941,1.283043,-0.226687,0.034772,0.889460,46.597368,72.342087,72.360420,68.00000
56,0.629941,1.283043,-0.226687,0.034772,1.482433,58.445445,82.499243,82.518054,72.28125
57,0.629941,1.283043,1.071610,0.034772,-1.482433,70.313070,35.840462,35.754602,51.34375
58,0.629941,1.283043,1.071610,0.034772,-0.889460,81.692693,45.997618,45.912236,56.84375
59,0.629941,1.283043,1.071610,0.034772,-0.296487,94.279900,56.154775,56.069870,61.56250
60,0.629941,1.283043,1.071610,0.034772,0.296487,25.130430,66.311932,66.227505,65.46875
61,0.629941,1.283043,1.071610,0.034772,0.889460,42.301917,76.469089,76.385139,68.56250
62,0.629941,0.374822,-1.524983,-1.717719,-0.296487,52.806249,52.021186,52.004724,54.18750
63,0.629941,0.374822,-1.524983,-1.717719,0.296487,63.341320,62.178343,62.162358,64.12500
64,0.629941,0.374822,-1.524983,-1.717719,0.889460,74.251849,72.335499,72.319992,73.31250
65,0.629941,0.374822,-1.524983,-1.717719,1.482433,85.933276,82.492656,82.477626,81.62500
66,0.629941,0.374822,-0.226687,0.911017,-1.482433,25.622520,30.665154,30.745863,33.00000
67,0.629941,0.374822,-0.226687,0.911017,-0.889460,42.163110,40.822311,40.903498,43.96875
68,0.629941,0.374822,-0.226687,0.911017,-0.296487,52.581945,50.979468,51.061132,54.12500
69,0.629941,0.374822,-0.226687,0.911017,0.296487,63.029908,61.136625,61.218766,63.43750
70,0.629941,0.374822,-0.226687,0.911017,0.889460,73.400707,71.293781,71.376400,71.96875
71,0.629941,0.374822,-0.226687,0.911017,1.482433,86.498412,81.450938,81.534034,79.68750
72,0.629941,0.374822,1.071610,0.911017,-1.482433,26.352900,34.792156,34.770582,37.81250
73,0.629941,0.374822,1.071610,0.911017,-0.889460,41.953703,44.949313,44.928216,46.81250
74,0.629941,0.374822,1.071610,0.911017,-0.296487,53.172718,55.106470,55.085851,54.96875
75,0.629941,0.374822,1.071610,0.911017,0.296487,64.423479,65.263627,65.243485,62.28125
76,0.629941,0.374822,1.071610,0.911017,0.889460,75.177924,75.420783,75.401119,68.84375
77,0.629941,0.374822,1.071610,0.911017,1.482433,87.731930,85.577940,85.558753,74.53125
78,0.629941,0.374822,-0.226687,0.034772,-1.482433,27.270810,32.388061,32.401967,38.37500
79,0.629941,0.374822,-0.226687,0.034772,-0.889460,45.265389,42.545218,42.559601,48.90625
80,0.629941,0.374822,-0.226687,0.034772,-0.296487,55.993895,52.702375,52.717235,58.59375
81,0.629941,0.374822,-0.226687,0.034772,0.296487,66.762966,62.859531,62.874870,67.46875
82,0.629941,0.374822,-0.226687,0.034772,0.889460,77.472379,73.016688,73.032504,75.56250
83,0.629941,0.374822,-0.226687,0.034772,1.482433,89.747944,83.173845,83.190138,82.81250
84,0.629941,0.374822,1.071610,0.034772,-1.482433,28.262040,36.515063,36.426686,46.68750
85,0.629941,0.374822,1.071610,0.034772,-0.889460,48.095192,46.672220,46.584320,55.21875
86,0.629941,0.374822,1.071610,0.034772,-0.296487,60.375724,56.829377,56.741954,62.90625
87,0.629941,0.374822,1.071610,0.034772,0.296487,72.691483,66.986533,66.899588,69.81250
88,0.629941,0.374822,1.071610,0.034772,0.889460,84.507782,77.143690,77.057223,75.87500
89,0.629941,0.374822,1.071610,0.034772,1.482433,97.600074,87.300847,87.214857,81.12500
90,-1.574852,-0.987511,-1.524983,-1.717719,-1.482433,25.325010,35.223661,35.211045,17.96875
91,-1.574852,-0.987511,-1.524983,-1.717719,-0.889460,42.567339,45.380818,45.368679,34.90625
92,-1.574852,-0.987511,-1.524983,-1.717719,-0.296487,53.017916,55.537975,55.526313,51.12500
93,-1.574852,-0.987511,-1.524983,-1.717719,0.296487,63.493134,65.695132,65.683947,66.43750
94,-1.574852,-0.987511,-1.524983,-1.717719,0.889460,73.924728,75.852288,75.841582,81.03125
95,-1.574852,-0.987511,-1.524983,-1.717719,1.482433,87.389588,86.009445,85.999216,94.71875
96,-1.574852,-0.987511,-0.226687,0.911017,-1.482433,25.848120,34.181943,34.267453,23.71875
97,-1.574852,-0.987511,-0.226687,0.911017,-0.889460,43.831137,44.339100,44.425087,40.03125
98,-1.574852,-0.987511,-0.226687,0.911017,-0.296487,55.937029,54.496257,54.582722,55.62500
99,-1.574852,-0.987511,-0.226687,0.911017,0.296487,67.634921,64.653413,64.740356,70.37500
100,-1.574852,-0.987511,-0.226687,0.911017,0.889460,79.061910,74.810570,74.897990,84.34375
101,-1.574852,-0.987511,-0.226687,0.911017,1.482433,92.263886,84.967727,85.055624,97.40625
102,-1.574852,-0.987511,1.071610,0.911017,-1.482433,26.625030,38.308945,38.292172,28.03125
103,-1.574852,-0.987511,1.071610,0.911017,-0.889460,45.129025,48.466102,48.449806,42.37500
104,-1.574852,-0.987511,1.071610,0.911017,-0.296487,57.399745,58.623259,58.607441,56.00000
105,-1.574852,-0.987511,1.071610,0.911017,0.296487,69.156950,68.780416,68.765075,68.75000
106,-1.574852,-0.987511,1.071610,0.911017,0.889460,80.434962,78.937572,78.922709,80.68750
107,-1.574852,-0.987511,1.071610,0.911017,1.482433,93.361554,89.094729,89.080343,91.78125
108,-1.574852,-0.987511,-0.226687,0.034772,-1.482433,27.602160,35.904850,35.923557,27.37500
109,-1.574852,-0.987511,-0.226687,0.034772,-0.889460,46.692336,46.062007,46.081191,43.21875
110,-1.574852,-0.987511,-0.226687,0.034772,-0.296487,59.690175,56.219164,56.238825,58.37500
111,-1.574852,-0.987511,-0.226687,0.034772,0.296487,71.905166,66.376320,66.396459,72.62500
112,-1.574852,-0.987511,-0.226687,0.034772,0.889460,83.249979,76.533477,76.554093,86.15625
113,-1.574852,-0.987511,-0.226687,0.034772,1.482433,97.105580,86.690634,86.711727,98.75000
114,-1.574852,-0.987511,1.071610,0.034772,-1.482433,27.950430,40.031852,39.948276,35.18750
115,-1.574852,-0.987511,1.071610,0.034772,-0.889460,47.744283,50.189009,50.105910,49.06250
116,-1.574852,-0.987511,1.071610,0.034772,-0.296487,61.070751,60.346166,60.263544,62.25000
117,-1.574852,-0.987511,1.071610,0.034772,0.296487,73.438873,70.503322,70.421178,74.50000
118,-1.574852,-0.987511,1.071610,0.034772,0.889460,85.756371,80.660479,80.578812,86.00000
119,-1.574852,-0.987511,1.071610,0.034772,1.482433,100.567038,90.817636,90.736446,96.62500
120,-1.574852,1.283043,-1.524983,-1.717719,-1.482433,25.818510,33.537158,33.530835,37.96875
121,-1.574852,1.283043,-1.524983,-1.717719,-0.889460,43.419611,43.694315,43.688469,47.40625
122,-1.574852,1.283043,-1.524983,-1.717719,-0.296487,54.123641,53.851472,53.846103,56.18750
123,-1.574852,1.283043,-1.524983,-1.717719,0.296487,64.855564,64.008628,64.003738,64.00000
124,-1.574852,1.283043,-1.524983,-1.717719,0.889460,75.998030,74.165785,74.161372,71.18750
125,-1.574852,1.283043,-1.524983,-1.717719,1.482433,87.884082,84.322942,84.319006,77.40625

In [30]:
y_pred_third = pd.DataFrame(y_pred, columns=['y_pred'])

df_normalized['nu_pred(3rd order)'] = y_pred_df['y_pred']

In [31]:
df_normalized

,x1,x2,x3,x4,x5,nu,nu_pred(LinearReg),nu_pred(gradient),nu_pred(2nd order),nu_pred(3rd order)
0,0.629941,-0.987511,-1.524983,-1.717719,-1.482433,24.058300,32.718774,32.697581,17.37500,17.37500
1,0.629941,-0.987511,-1.524983,-1.717719,-0.889460,40.439094,42.875931,42.855215,33.43750,33.43750
2,0.629941,-0.987511,-1.524983,-1.717719,-0.296487,50.367336,53.033088,53.012850,48.68750,48.68750
3,0.629941,-0.987511,-1.524983,-1.717719,0.296487,60.316725,63.190245,63.170484,63.12500,63.12500
4,0.629941,-0.987511,-1.524983,-1.717719,0.889460,70.229644,73.347401,73.328118,76.75000,76.75000
5,0.629941,-0.987511,-1.524983,-1.717719,1.482433,83.020652,83.504558,83.485752,89.59375,89.59375
6,0.629941,-0.987511,-0.226687,0.911017,-1.482433,24.555150,31.677056,31.753989,22.40625,22.40625
7,0.629941,-0.987511,-0.226687,0.911017,-0.889460,41.639580,41.834213,41.911623,37.84375,37.84375
8,0.629941,-0.987511,-0.226687,0.911017,-0.296487,53.141126,51.991370,52.069258,52.50000,52.50000
9,0.629941,-0.987511,-0.226687,0.911017,0.296487,64.252202,62.148526,62.226892,66.31250,66.31250
10,0.629941,-0.987511,-0.226687,0.911017,0.889460,75.108814,72.305683,72.384526,79.31250,79.31250
11,0.629941,-0.987511,-0.226687,0.911017,1.482433,87.650420,82.462840,82.542160,91.53125,91.53125
12,0.629941,-0.987511,1.071610,0.911017,-1.482433,25.293990,35.804058,35.778708,26.90625,26.90625
13,0.629941,-0.987511,1.071610,0.911017,-0.889460,42.871722,45.961215,45.936342,40.34375,40.34375
14,0.629941,-0.987511,1.071610,0.911017,-0.296487,54.531179,56.118372,56.093977,53.00000,53.00000
15,0.629941,-0.987511,1.071610,0.911017,0.296487,65.700271,66.275529,66.251611,64.84375,64.84375
16,0.629941,-0.987511,1.071610,0.911017,0.889460,76.412691,76.432685,76.409245,75.84375,75.84375
17,0.629941,-0.987511,1.071610,0.911017,1.482433,88.693748,86.589842,86.566879,86.06250,86.06250
18,0.629941,-0.987511,-0.226687,0.034772,-1.482433,26.221770,33.399963,33.410093,26.40625,26.40625
19,0.629941,-0.987511,-0.226687,0.034772,-0.889460,44.357110,43.557120,43.567727,41.40625,41.40625
20,0.629941,-0.987511,-0.226687,0.034772,-0.296487,56.704718,53.714277,53.725361,55.59375,55.59375
21,0.629941,-0.987511,-0.226687,0.034772,0.296487,68.308351,63.871433,63.882996,68.93750,68.93750
22,0.629941,-0.987511,-0.226687,0.034772,0.889460,79.089554,74.028590,74.040630,81.50000,81.50000
23,0.629941,-0.987511,-0.226687,0.034772,1.482433,92.253018,84.185747,84.198264,93.25000,93.25000
24,0.629941,-0.987511,1.071610,0.034772,-1.482433,26.553120,37.526965,37.434812,34.37500,34.37500
25,0.629941,-0.987511,1.071610,0.034772,-0.889460,45.357921,47.684122,47.592446,47.37500,47.37500
26,0.629941,-0.987511,1.071610,0.034772,-0.296487,58.015792,57.841279,57.750080,59.59375,59.59375
27,0.629941,-0.987511,1.071610,0.034772,0.296487,69.768098,67.998435,67.907714,70.93750,70.93750
28,0.629941,-0.987511,1.071610,0.034772,0.889460,81.466940,78.155592,78.065349,81.53125,81.53125
29,0.629941,-0.987511,1.071610,0.034772,1.482433,95.540588,88.312749,88.222983,91.28125,91.28125
30,0.629941,1.283043,-1.524983,-1.717719,-1.482433,24.268920,31.032271,31.017371,37.93750,37.93750
31,0.629941,1.283043,-1.524983,-1.717719,-0.889460,40.814093,41.189428,41.175005,46.53125,46.53125
32,0.629941,1.283043,-1.524983,-1.717719,-0.296487,50.875970,51.346585,51.332640,54.31250,54.31250
33,0.629941,1.283043,-1.524983,-1.717719,0.296487,60.962907,61.503741,61.490274,61.25000,61.25000
34,0.629941,1.283043,-1.524983,-1.717719,0.889460,71.436766,71.660898,71.647908,67.37500,67.37500
35,0.629941,1.283043,-1.524983,-1.717719,1.482433,82.611302,81.818055,81.805542,72.75000,72.75000
36,0.629941,1.283043,-0.226687,0.911017,-1.482433,24.761010,29.990553,30.073779,36.50000,36.50000
37,0.629941,1.283043,-0.226687,0.911017,-0.889460,40.675295,40.147709,40.231414,44.46875,44.46875
38,0.629941,1.283043,-0.226687,0.911017,-0.296487,50.651666,50.304866,50.389048,51.62500,51.62500
39,0.629941,1.283043,-0.226687,0.911017,0.296487,60.651494,60.462023,60.546682,57.96875,57.96875
40,0.629941,1.283043,-0.226687,0.911017,0.889460,70.593623,70.619180,70.704316,63.50000,63.50000
41,0.629941,1.283043,-0.226687,0.911017,1.482433,83.178239,80.776337,80.861950,68.25000,68.25000
42,0.629941,1.283043,1.071610,0.911017,-1.482433,25.491390,34.117555,34.098498,41.53125,41.53125
43,0.629941,1.283043,1.071610,0.911017,-0.889460,40.465794,44.274712,44.256132,47.50000,47.50000
44,0.629941,1.283043,1.071610,0.911017,-0.296487,51.242438,54.431869,54.413767,52.68750,52.68750
45,0.629941,1.283043,1.071610,0.911017,0.296487,62.045065,64.589025,64.571401,57.03125,57.03125
46,0.629941,1.283043,1.071610,0.911017,-0.889460,72.362841,44.274712,44.256132,47.50000,47.50000
47,0.629941,1.283043,1.071610,0.911017,-0.296487,84.411756,54.431869,54.413767,52.68750,52.68750
48,0.629941,1.283043,1.071610,0.911017,0.296487,26.409300,64.589025,64.571401,57.03125,57.03125
49,0.629941,1.283043,1.071610,0.911017,0.889460,43.777565,74.746182,74.729035,60.56250,60.56250
50,0.629941,1.283043,1.071610,0.911017,1.482433,54.063616,84.903339,84.886669,63.31250,63.31250
51,0.629941,1.283043,-0.226687,0.034772,-1.482433,64.384552,31.713460,31.729883,42.81250,42.81250
52,0.629941,1.283043,-0.226687,0.034772,-0.889460,74.657295,41.870616,41.887517,50.34375,50.34375
53,0.629941,1.283043,-0.226687,0.034772,-0.296487,86.427770,52.027773,52.045151,57.03125,57.03125
54,0.629941,1.283043,-0.226687,0.034772,0.296487,27.400530,62.184930,62.202786,62.93750,62.93750
55,0.629941,1.283043,-0.226687,0.034772,0.889460,46.597368,72.342087,72.360420,68.00000,68.00000
56,0.629941,1.283043,-0.226687,0.034772,1.482433,58.445445,82.499243,82.518054,72.28125,72.28125
57,0.629941,1.283043,1.071610,0.034772,-1.482433,70.313070,35.840462,35.754602,51.34375,51.34375
58,0.629941,1.283043,1.071610,0.034772,-0.889460,81.692693,45.997618,45.912236,56.84375,56.84375
59,0.629941,1.283043,1.071610,0.034772,-0.296487,94.279900,56.154775,56.069870,61.56250,61.56250
60,0.629941,1.283043,1.071610,0.034772,0.296487,25.130430,66.311932,66.227505,65.46875,65.46875
61,0.629941,1.283043,1.071610,0.034772,0.889460,42.301917,76.469089,76.385139,68.56250,68.56250
62,0.629941,0.374822,-1.524983,-1.717719,-0.296487,52.806249,52.021186,52.004724,54.18750,54.18750
63,0.629941,0.374822,-1.524983,-1.717719,0.296487,63.341320,62.178343,62.162358,64.12500,64.12500
64,0.629941,0.374822,-1.524983,-1.717719,0.889460,74.251849,72.335499,72.319992,73.31250,73.31250
65,0.629941,0.374822,-1.524983,-1.717719,1.482433,85.933276,82.492656,82.477626,81.62500,81.62500
66,0.629941,0.374822,-0.226687,0.911017,-1.482433,25.622520,30.665154,30.745863,33.00000,33.00000
67,0.629941,0.374822,-0.226687,0.911017,-0.889460,42.163110,40.822311,40.903498,43.96875,43.96875
68,0.629941,0.374822,-0.226687,0.911017,-0.296487,52.581945,50.979468,51.061132,54.12500,54.12500
69,0.629941,0.374822,-0.226687,0.911017,0.296487,63.029908,61.136625,61.218766,63.43750,63.43750
70,0.629941,0.374822,-0.226687,0.911017,0.889460,73.400707,71.293781,71.376400,71.96875,71.96875
71,0.629941,0.374822,-0.226687,0.911017,1.482433,86.498412,81.450938,81.534034,79.68750,79.68750
72,0.629941,0.374822,1.071610,0.911017,-1.482433,26.352900,34.792156,34.770582,37.81250,37.81250
73,0.629941,0.374822,1.071610,0.911017,-0.889460,41.953703,44.949313,44.928216,46.81250,46.81250
74,0.629941,0.374822,1.071610,0.911017,-0.296487,53.172718,55.106470,55.085851,54.96875,54.96875
75,0.629941,0.374822,1.071610,0.911017,0.296487,64.423479,65.263627,65.243485,62.28125,62.28125
76,0.629941,0.374822,1.071610,0.911017,0.889460,75.177924,75.420783,75.401119,68.84375,68.84375
77,0.629941,0.374822,1.071610,0.911017,1.482433,87.731930,85.577940,85.558753,74.53125,74.53125
78,0.629941,0.374822,-0.226687,0.034772,-1.482433,27.270810,32.388061,32.401967,38.37500,38.37500
79,0.629941,0.374822,-0.226687,0.034772,-0.889460,45.265389,42.545218,42.559601,48.90625,48.90625
80,0.629941,0.374822,-0.226687,0.034772,-0.296487,55.993895,52.702375,52.717235,58.59375,58.59375
81,0.629941,0.374822,-0.226687,0.034772,0.296487,66.762966,62.859531,62.874870,67.46875,67.46875
82,0.629941,0.374822,-0.226687,0.034772,0.889460,77.472379,73.016688,73.032504,75.56250,75.56250
83,0.629941,0.374822,-0.226687,0.034772,1.482433,89.747944,83.173845,83.190138,82.81250,82.81250
84,0.629941,0.374822,1.071610,0.034772,-1.482433,28.262040,36.515063,36.426686,46.68750,46.68750
85,0.629941,0.374822,1.071610,0.034772,-0.889460,48.095192,46.672220,46.584320,55.21875,55.21875
86,0.629941,0.374822,1.071610,0.034772,-0.296487,60.375724,56.829377,56.741954,62.90625,62.90625
87,0.629941,0.374822,1.071610,0.034772,0.296487,72.691483,66.986533,66.899588,69.81250,69.81250
88,0.629941,0.374822,1.071610,0.034772,0.889460,84.507782,77.143690,77.057223,75.87500,75.87500
89,0.629941,0.374822,1.071610,0.034772,1.482433,97.600074,87.300847,87.214857,81.12500,81.12500
90,-1.574852,-0.987511,-1.524983,-1.717719,-1.482433,25.325010,35.223661,35.211045,17.96875,17.96875
91,-1.574852,-0.987511,-1.524983,-1.717719,-0.889460,42.567339,45.380818,45.368679,34.90625,34.90625
92,-1.574852,-0.987511,-1.524983,-1.717719,-0.296487,53.017916,55.537975,55.526313,51.12500,51.12500
93,-1.574852,-0.987511,-1.524983,-1.717719,0.296487,63.493134,65.695132,65.683947,66.43750,66.43750
94,-1.574852,-0.987511,-1.524983,-1.717719,0.889460,73.924728,75.852288,75.841582,81.03125,81.03125
95,-1.574852,-0.987511,-1.524983,-1.717719,1.482433,87.389588,86.009445,85.999216,94.71875,94.71875
96,-1.574852,-0.987511,-0.226687,0.911017,-1.482433,25.848120,34.181943,34.267453,23.71875,23.71875
97,-1.574852,-0.987511,-0.226687,0.911017,-0.889460,43.831137,44.339100,44.425087,40.03125,40.03125
98,-1.574852,-0.987511,-0.226687,0.911017,-0.296487,55.937029,54.496257,54.582722,55.62500,55.62500
99,-1.574852,-0.987511,-0.226687,0.911017,0.296487,67.634921,64.653413,64.740356,70.37500,70.37500
100,-1.574852,-0.987511,-0.226687,0.911017,0.889460,79.061910,74.810570,74.897990,84.34375,84.34375
101,-1.574852,-0.987511,-0.226687,0.911017,1.482433,92.263886,84.967727,85.055624,97.40625,97.40625
102,-1.574852,-0.987511,1.071610,0.911017,-1.482433,26.625030,38.308945,38.292172,28.03125,28.03125
103,-1.574852,-0.987511,1.071610,0.911017,-0.889460,45.129025,48.466102,48.449806,42.37500,42.37500
104,-1.574852,-0.987511,1.071610,0.911017,-0.296487,57.399745,58.623259,58.607441,56.00000,56.00000
105,-1.574852,-0.987511,1.071610,0.911017,0.296487,69.156950,68.780416,68.765075,68.75000,68.75000
106,-1.574852,-0.987511,1.071610,0.911017,0.889460,80.434962,78.937572,78.922709,80.68750,80.68750
107,-1.574852,-0.987511,1.071610,0.911017,1.482433,93.361554,89.094729,89.080343,91.78125,91.78125
108,-1.574852,-0.987511,-0.226687,0.034772,-1.482433,27.602160,35.904850,35.923557,27.37500,27.37500
109,-1.574852,-0.987511,-0.226687,0.034772,-0.889460,46.692336,46.062007,46.081191,43.21875,43.21875
110,-1.574852,-0.987511,-0.226687,0.034772,-0.296487,59.690175,56.219164,56.238825,58.37500,58.37500
111,-1.574852,-0.987511,-0.226687,0.034772,0.296487,71.905166,66.376320,66.396459,72.62500,72.62500
112,-1.574852,-0.987511,-0.226687,0.034772,0.889460,83.249979,76.533477,76.554093,86.15625,86.15625
113,-1.574852,-0.987511,-0.226687,0.034772,1.482433,97.105580,86.690634,86.711727,98.75000,98.75000
114,-1.574852,-0.987511,1.071610,0.034772,-1.482433,27.950430,40.031852,39.948276,35.18750,35.18750
115,-1.574852,-0.987511,1.071610,0.034772,-0.889460,47.744283,50.189009,50.105910,49.06250,49.06250
116,-1.574852,-0.987511,1.071610,0.034772,-0.296487,61.070751,60.346166,60.263544,62.25000,62.25000
117,-1.574852,-0.987511,1.071610,0.034772,0.296487,73.438873,70.503322,70.421178,74.50000,74.50000
118,-1.574852,-0.987511,1.071610,0.034772,0.889460,85.756371,80.660479,80.578812,86.00000,86.00000
119,-1.574852,-0.987511,1.071610,0.034772,1.482433,100.567038,90.817636,90.736446,96.62500,96.62500
120,-1.574852,1.283043,-1.524983,-1.717719,-1.482433,25.818510,33.537158,33.530835,37.96875,37.96875
121,-1.574852,1.283043,-1.524983,-1.717719,-0.889460,43.419611,43.694315,43.688469,47.40625,47.40625
122,-1.574852,1.283043,-1.524983,-1.717719,-0.296487,54.123641,53.851472,53.846103,56.18750,56.18750
123,-1.574852,1.283043,-1.524983,-1.717719,0.296487,64.855564,64.008628,64.003738,64.00000,64.00000
124,-1.574852,1.283043,-1.524983,-1.717719,0.889460,75.998030,74.165785,74.161372,71.18750,71.18750
125,-1.574852,1.283043,-1.524983,-1.717719,1.482433,87.884082,84.322942,84.319006,77.40625,77.40625

In [34]:
df_normalized.to_excel("data/Prediction Comparison.xlsx",index=False)