# Setting and resetting the index

In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df['email']

0    person007@example.com
1          person014@example.com
2          person015@example.com
Name: email, dtype: object

In [6]:
df.set_index('email')

                         first     last
email
person007@example.com  Corey  Schafer
person014@example.com         Jane      Doe
person015@example.com         John      Doe

In [7]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [8]:
df.set_index('email',inplace=True)
df

                         first     last
email
person007@example.com  Corey  Schafer
person014@example.com         Jane      Doe
person015@example.com         John      Doe

In [9]:
df.index

Index(['person007@example.com', 'person014@example.com', 'person015@example.com'], dtype='object', name='email')

In [10]:
df.loc['person007@example.com']

first      Corey
last     Schafer
Name: person007@example.com, dtype: object

In [11]:
df.loc['person007@example.com','last']

'Schafer'

In [12]:
df.iloc[0]

first      Corey
last     Schafer
Name: person007@example.com, dtype: object

In [13]:
df.reset_index(inplace=True)
df

                     email  first     last
0  person007@example.com  Corey  Schafer
1        person014@example.com   Jane      Doe
2        person015@example.com   John      Doe