In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df.columns = ['first_name', 'last_name', 'email']

In [6]:
df

  first_name last_name                    email
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com

In [7]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'},inplace=True)

In [8]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [9]:
df.loc[2]=['John','Smith','person017@example.com']

In [10]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith      person017@example.com

In [11]:
df.loc[2,['last','email']]=['Doe','person016@example.com']

In [12]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person016@example.com

In [13]:
df.loc[2,'last']='smith'

In [14]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    smith        person016@example.com

In [15]:
filt=(df['email']=='person016@example.com')
df[filt]['last']='smith'

In [16]:
filt=(df['email']=='person016@example.com')
df.loc[filt,'last']='Smith'

In [17]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John    Smith        person016@example.com

In [18]:
df['email']=df['email'].str.lower()

In [19]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person025@example.com

In [20]:
df['email'].apply(len)

0    23
1    17
2    17
Name: email, dtype: int64

In [21]:
def update_email(email):
    return email.upper()

In [22]:
df['email'].apply(update_email)

0    person003@example.com
1          person011@example.com
2          person013@example.com
Name: email, dtype: object

In [23]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person025@example.com

In [24]:
df['email']=df['email'].apply(update_email)

In [25]:
df

   first     last                    email
0  Corey  Schafer  person003@example.com
1   Jane      Doe        person011@example.com
2   John    Smith        person013@example.com

In [26]:
df['email']=df['email'].apply(lambda x:x.lower())

In [27]:
df

   first     last                    email
0  Corey  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John    Smith        person025@example.com

In [28]:
df.apply(pd.Series.min)

first                      Corey
last                         Doe
email    person021@example.com
dtype: object

In [29]:
df.applymap(str.lower)

   first     last                    email
0  corey  schafer  person021@example.com
1   jane      doe        person023@example.com
2   john    smith        person025@example.com

In [30]:
df['first']=df['first'].map({'Corey': 'Chris', 'Jane': 'Mary'})

In [31]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Mary      Doe        person023@example.com
2    NaN    Smith        person025@example.com

In [32]:
df['first']=df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})

In [33]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Mary      Doe        person023@example.com
2    NaN    Smith        person025@example.com

In [34]:
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [35]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Mary      Doe        person023@example.com
2    NaN    Smith        person025@example.com

In [36]:
df.loc[2]=['John','Doe','person025@example.com']
df.loc[1,'first']='Jane'

In [37]:
df

   first     last                    email
0  Chris  Schafer  person021@example.com
1   Jane      Doe        person023@example.com
2   John      Doe        person025@example.com

In [38]:
df['first'] + ' ' + df['last']

0    Chris Schafer
1         Jane Doe
2         John Doe
dtype: object

In [39]:
df['full_name']=df['first'] + ' ' + df['last']

In [40]:
df

   first     last                    email      full_name
0  Chris  Schafer  person021@example.com  Chris Schafer
1   Jane      Doe        person023@example.com       Jane Doe
2   John      Doe        person025@example.com       John Doe

In [41]:
df.drop(columns=['first','last'],inplace=True)

In [42]:
df

                     email      full_name
0  person021@example.com  Chris Schafer
1        person023@example.com       Jane Doe
2        person025@example.com       John Doe

In [43]:
df['full_name'].str.split(' ')

0    [Chris, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [44]:
df['full_name'].str.split(' ',expand=True)

       0        1
0  Chris  Schafer
1   Jane      Doe
2   John      Doe

In [45]:
df[['first','last']]=df['full_name'].str.split(' ',expand=True)

In [46]:
df

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe

In [47]:
df._append({'first':'Tony'},ignore_index=True)

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [48]:
people = {
    'first': ['Tony', 'Steve'], 
    'last': ['Stark', 'Rogers'], 
    'email': ['person009@example.com', 'person005@example.com']
}
df2 = pd.DataFrame(people)

In [49]:
df2

   first    last               email
0   Tony   Stark  person009@example.com
1  Steve  Rogers      person005@example.com

In [50]:
df._append(df2,ignore_index=True)

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe
3       person009@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [51]:
df

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe

In [52]:
df=df._append(df2,ignore_index=True)

In [53]:
df

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe
3       person009@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [54]:
df.drop(index=4)

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe
3       person009@example.com            NaN   Tony    Stark

In [55]:
filt=df['last']=='Doe'
df.drop(index=df[filt].index)

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
3       person009@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [56]:
df

                     email      full_name  first     last
0  person021@example.com  Chris Schafer  Chris  Schafer
1        person023@example.com       Jane Doe   Jane      Doe
2        person025@example.com       John Doe   John      Doe
3       person009@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers