In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("data/survey_results_public.csv",index_col='Respondent')
schema_df = pd.read_csv("data/survey_results_schema.csv",index_col='Column')

In [4]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [26]:
schema_df.head(80)

                                                    QuestionText
Column
Respondent     Randomized respondent ID number (not in order ...
MainBranch     Which of the following options best describes ...
Hobbyist                                 Do you code as a hobby?
OpenSourcer          How often do you contribute to open source?
OpenSource     How do you feel about the quality of open sour...
...                                                          ...
WelcomeChange  Compared to last year, how welcome do you feel...
SONewContent   Would you like to see any of the following on ...
Age            What is your age (in years)? If you prefer not...
Gender         Which of the following do you currently identi...
Trans                            Do you identify as transgender?

[80 rows x 1 columns]

In [10]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
11         NaN
12         NaN
13     90000.0
14     57060.0
15         NaN
Name: ConvertedComp, dtype: float64

In [12]:
df['ConvertedComp'].median()

57287.0

In [14]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [15]:
df['ConvertedComp'].count()

55823

In [16]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [18]:
df['Hobbyist'].count()

88883

In [20]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: count, dtype: int64

In [29]:
schema_df.loc['SONewContent','QuestionText']

'Would you like to see any of the following on Stack Overflow? Check all that apply.'

In [31]:
df['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [32]:
yo=df.groupby(['Country'])

In [33]:
yo

In [38]:
yo.get_group('Germany')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,31.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too short,Easy
36,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Germany,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,NaN,21.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
66,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Neither easy nor difficult
85,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,31.0,Man,No,Straight / Heterosexual,White or of European descent,NaN,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64465,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,NaN,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
71055,NaN,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, and not looking for work",Germany,No,NaN,"A social science (ex. anthropology, psychology...",Contributed to open source software,...,A lot more welcome now than last year,Industry news about technologies you're intere...,2.0,Man,NaN,NaN,NaN,NaN,Too long,Difficult
75974,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,NaN,Man,No,NaN,Middle Eastern,Yes,Appropriate in length,Easy
80319,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,18.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult

In [43]:
filt=(df['Country']=='Germany')
df.loc[filt]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,31.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too short,Easy
36,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Germany,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,NaN,21.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
66,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Neither easy nor difficult
85,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,31.0,Man,No,Straight / Heterosexual,White or of European descent,NaN,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64465,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,NaN,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
71055,NaN,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, and not looking for work",Germany,No,NaN,"A social science (ex. anthropology, psychology...",Contributed to open source software,...,A lot more welcome now than last year,Industry news about technologies you're intere...,2.0,Man,NaN,NaN,NaN,NaN,Too long,Difficult
75974,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,NaN,Man,No,NaN,Middle Eastern,Yes,Appropriate in length,Easy
80319,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Germany,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,18.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult

In [50]:
filt=(df['Country']=='Bangladesh')
df.loc[filt]['SocialMedia'].value_counts()

SocialMedia
Facebook                    313
YouTube                     137
LinkedIn                     62
Twitter                      19
I don't use social media     17
WhatsApp                     14
Reddit                        9
Instagram                     8
Snapchat                      2
VK ВКонта́кте                 1
Name: count, dtype: int64

In [52]:
yo['SocialMedia'].value_counts().head(15)

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
             LinkedIn                     1
             Twitter                      1
Albania      WhatsApp                    18
             Facebook                    16
             Instagram                   13
             YouTube                     10
             Twitter                      8
             LinkedIn                     7
             Reddit                       6
             I don't use social media     4
Name: count, dtype: int64

In [53]:
yo['Hobbyist'].value_counts().head(15)

Country              Hobbyist
Afghanistan          Yes          29
                     No           15
Albania              Yes          70
                     No           16
Algeria              Yes          98
                     No           36
Andorra              Yes           4
                     No            3
Angola               Yes           4
                     No            1
Antigua and Barbuda  Yes           5
                     No            4
Argentina            Yes         398
                     No          155
Armenia              Yes          54
Name: count, dtype: int64

In [57]:
df.loc[2]

MainBranch                 I am a student who is learning to code
Hobbyist                                                       No
OpenSourcer                               Less than once per year
OpenSource      The quality of OSS and closed source software ...
Employment                     Not employed, but looking for work
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 2, Length: 84, dtype: object

In [60]:
yo['SocialMedia'].value_counts(normalize=True).loc['Bangladesh']

SocialMedia
Facebook                    0.537801
YouTube                     0.235395
LinkedIn                    0.106529
Twitter                     0.032646
I don't use social media    0.029210
WhatsApp                    0.024055
Reddit                      0.015464
Instagram                   0.013746
Snapchat                    0.003436
VK ВКонта́кте               0.001718
Name: proportion, dtype: float64

In [61]:
yo['ConvertedComp'].agg(['median','mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [62]:
yo['ConvertedComp'].agg(['median','mean']).loc['Bangladesh']

median     8764.000
mean      21249.652
Name: Bangladesh, dtype: float64

In [63]:
filt=(df['Country']=='India')
df.loc[filt]['LanguageWorkedWith'].str.contains('Python')

Respondent
8         True
10        True
15       False
50        True
65       False
         ...
77339    False
79795     True
83862    False
84299     True
86012    False
Name: LanguageWorkedWith, Length: 9061, dtype: object

In [64]:
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [65]:
yo['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [66]:
CR=df['Country'].value_counts()
CR

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [67]:
py=yo['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
py

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [68]:
python_df=pd.concat([CR,py],axis='columns')
python_df

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [69]:
python_df.rename(columns={'count':'NumRespondents','LanguageWorkedWith':'NumKnowsPython'},inplace=True)

In [71]:
python_df

                   NumRespondents  NumKnowsPython
Country
United States               20949           10083
India                        9061            3105
Germany                      5866            2451
United Kingdom               5737            2384
Canada                       3395            1558
...                           ...             ...
Tonga                           1               0
Timor-Leste                     1               1
North Korea                     1               0
Brunei Darussalam               1               0
Chad                            1               0

[179 rows x 2 columns]

In [72]:
python_df['PctKnowsPython']=(python_df['NumKnowsPython']/python_df['NumRespondents'])*100

In [73]:
python_df

                   NumRespondents  NumKnowsPython  PctKnowsPython
Country
United States               20949           10083       48.131176
India                        9061            3105       34.267741
Germany                      5866            2451       41.783157
United Kingdom               5737            2384       41.554820
Canada                       3395            1558       45.891016
...                           ...             ...             ...
Tonga                           1               0        0.000000
Timor-Leste                     1               1      100.000000
North Korea                     1               0        0.000000
Brunei Darussalam               1               0        0.000000
Chad                            1               0        0.000000

[179 rows x 3 columns]

In [74]:
python_df.sort_values(by='PctKnowsPython',ascending=False,inplace=True)

In [75]:
python_df

,NumRespondents,NumKnowsPython,PctKnowsPython
Country,,,
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Niger,1,1,100.000000
Turkmenistan,7,6,85.714286
...,...,...,...
Cape Verde,3,0,0.000000
Lao People's Democratic Republic,3,0,0.000000
Malawi,2,0,0.000000
Liberia,2,0,0.000000
Chad,1,0,0.000000

In [76]:
python_df.head(50)

,NumRespondents,NumKnowsPython,PctKnowsPython
Country,,,
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Niger,1,1,100.000000
Turkmenistan,7,6,85.714286
Mauritania,7,5,71.428571
Guinea,3,2,66.666667
Bahamas,3,2,66.666667
Guyana,3,2,66.666667
Uganda,72,47,65.277778
Iceland,49,30,61.224490
Haiti,5,3,60.000000
Benin,5,3,60.000000
Namibia,5,3,60.000000
"Congo, Republic of the...",7,4,57.142857
Oman,11,6,54.545455
Cuba,30,16,53.333333
Republic of Korea,39,20,51.282051
San Marino,2,1,50.000000
Sierra Leone,2,1,50.000000
Monaco,4,2,50.000000
South Korea,160,80,50.000000
Bhutan,2,1,50.000000
Seychelles,2,1,50.000000
Chile,206,102,49.514563
Finland,546,266,48.717949
Kenya,249,120,48.192771
United States,20949,10083,48.131176
Israel,952,457,48.004202
Ecuador,82,39,47.560976
Taiwan,187,88,47.058824
Montenegro,17,8,47.058824
Mongolia,17,8,47.058824
Switzerland,978,460,47.034765
United Republic of Tanzania,32,15,46.875000
Hong Kong (S.A.R.),188,88,46.808511
Japan,391,182,46.547315
Maldives,13,6,46.153846
Canada,3395,1558,45.891016
Singapore,303,139,45.874587
New Zealand,524,236,45.038168
China,664,297,44.728916
Honduras,27,12,44.444444
France,2391,1054,44.081974
Iraq,39,17,43.589744
Thailand,214,92,42.990654
Democratic Republic of the Congo,7,3,42.857143
Nepal,237,101,42.616034
Estonia,195,82,42.051282
Russian Federation,1694,708,41.794569

In [79]:
python_df.loc[['Japan','Bangladesh']]

            NumRespondents  NumKnowsPython  PctKnowsPython
Country
Japan                  391             182       46.547315
Bangladesh             605             204       33.719008