In [1]:
person = {
    "first": "Corey", 
    "last": "Schafer", 
    "email": "person007@example.com"
}

In [2]:
people = {
    "first": ["Corey"], 
    "last": ["Schafer"], 
    "email": ["person007@example.com"]
}

In [3]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [4]:
people['email']

['person007@example.com', 'person014@example.com', 'person015@example.com']

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(people)

In [7]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [8]:
df['email']

0    person007@example.com
1          person014@example.com
2          person015@example.com
Name: email, dtype: object

In [9]:
df.email

0    person007@example.com
1          person014@example.com
2          person015@example.com
Name: email, dtype: object

In [10]:
df[['last', 'email']]

      last                    email
0  Schafer  person007@example.com
1      Doe        person014@example.com
2      Doe        person015@example.com

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [12]:
df.iloc[[0, 1], 2]

0    person007@example.com
1          person014@example.com
Name: email, dtype: object

In [13]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [14]:
df.loc[[0, 1], ['email', 'last']]

                     email     last
0  person007@example.com  Schafer
1        person014@example.com      Doe