In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [6]:
df.rename(columns={'first':'first_name','last':'last_name'},inplace=True)

In [7]:
df

  first_name last_name                    email
0      Corey   Schafer  person007@example.com
1       Jane       Doe        person014@example.com
2       John       Doe        person015@example.com