In [5]:
import pandas as pd

In [6]:
url ='https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv'
df = pd.read_csv(url)
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [8]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)

In [11]:
dfnew=pd.DataFrame(X_train_count)
dfnew

                                                      0
0       (0, 3995)\t1\n  (0, 3220)\t1\n  (0, 6615)\t2...
1       (0, 3376)\t1\n  (0, 5987)\t1\n  (0, 1064)\t1...
2       (0, 4443)\t1\n  (0, 3593)\t1\n  (0, 7328)\t1...
3       (0, 6615)\t1\n  (0, 6495)\t1\n  (0, 1932)\t1...
4       (0, 3593)\t1\n  (0, 7102)\t1\n  (0, 6898)\t1...
...                                                 ...
4174    (0, 3220)\t1\n  (0, 6615)\t2\n  (0, 3593)\t1...
4175    (0, 1838)\t1\n  (0, 5012)\t1\n  (0, 1582)\t1...
4176    (0, 3605)\t1\n  (0, 3593)\t1\n  (0, 7344)\t1...
4177    (0, 2825)\t1\n  (0, 6496)\t2\n  (0, 7062)\t1...
4178    (0, 6615)\t1\n  (0, 2825)\t2\n  (0, 3593)\t1...

[4179 rows x 1 columns]

In [12]:
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

**Gaussian Naive Bias**

In [33]:
# X_train = [[25, 120, 180], [45, 140, 200], [35, 130, 190]]
# y_train = [0, 1, 0]  # 0: No disease, 1: Disease

# model = GaussianNB()

# X_test = [[30, 125, 185]]
# prediction = model.predict(X_test)

array([0])

**Multinomial Naive Bias**

In [1]:
# labels = [1, 1, 0, 0]  # 1: Spam, 0: Not spam

# vectorizer = CountVectorizer()
# X_train = vectorizer.fit_transform(emails)

# model = MultinomialNB()

# new_email = ["Cheap drugs available now"]
# X_test = vectorizer.transform(new_email)
# prediction = model.predict(X_test)

In [16]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [18]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [19]:
X_test

1503                           Don no da:)whats you plan?
1283    Ever green quote ever told by Jerry in cartoon...
1947    Hey we can go jazz power yoga hip hop kb and y...
3177    Havent still waitin as usual... Ü come back sc...
2466                       S.i think he is waste for rr..
                              ...
3364                                   Can... I'm free...
3407    HEY DAS COOL... IKNOW ALL 2 WELLDA PERIL OF ST...
3834    I had askd u a question some hours before. Its...
4565                   Tell me again what your address is
509                              What's the significance?
Name: Message, Length: 1393, dtype: object

In [20]:
df.loc[1503]

Category                           ham
Message     Don no da:)whats you plan?
spam                                 0
Name: 1503, dtype: object

In [30]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9827709978463748

**Sklearn Pipeline**

In [31]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [32]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [33]:
clf.score(X_test,y_test)

0.9827709978463748

In [34]:
clf.predict(emails)

array([0, 1], dtype=int64)

## Sources

Source: [Codebasics](https://github.com/codebasics/py).