In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df['last']=='Doe'

0    False
1     True
2     True
Name: last, dtype: bool

In [6]:
filt=(df['last']=='Doe')

In [7]:
df[filt]

  first last              email
1  Jane  Doe  person014@example.com
2  John  Doe  person015@example.com

In [8]:
df.loc[filt]

  first last              email
1  Jane  Doe  person014@example.com
2  John  Doe  person015@example.com

In [9]:
filt=(df['last']=='Doe')&(df['first']=='Jane')

In [10]:
df[filt]

  first last              email
1  Jane  Doe  person014@example.com

In [11]:
df[-filt]

   first     last                    email
0  Corey  Schafer  person007@example.com
2   John      Doe        person015@example.com