# Adding and removing rows and columns

In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df['first']+' '+df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: object

In [6]:
df['full_name']=df['first']+' '+df['last']

In [7]:
df

   first     last                    email      full_name
0  Corey  Schafer  person007@example.com  Corey Schafer
1   Jane      Doe        person014@example.com       Jane Doe
2   John      Doe        person015@example.com       John Doe

In [8]:
df.drop(columns=['first','last'])

                     email      full_name
0  person007@example.com  Corey Schafer
1        person014@example.com       Jane Doe
2        person015@example.com       John Doe

In [9]:
df

   first     last                    email      full_name
0  Corey  Schafer  person007@example.com  Corey Schafer
1   Jane      Doe        person014@example.com       Jane Doe
2   John      Doe        person015@example.com       John Doe

In [10]:
df.drop(columns=['first','last'],inplace=True)

In [11]:
df

                     email      full_name
0  person007@example.com  Corey Schafer
1        person014@example.com       Jane Doe
2        person015@example.com       John Doe

In [12]:
df['full_name'].str.split(' ')

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: full_name, dtype: object

In [13]:
df['full_name'].str.split(' ',expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [14]:
df[['first','last']]=df['full_name'].str.split(' ',expand=True)

In [15]:
df

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe

In [16]:
pd.concat([df, pd.DataFrame([{'first':'Tony'}])], ignore_index=True)

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [17]:
df._append({'first':'Tony'},ignore_index=True)

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [18]:
people = {
    "first": ["Tony", 'Steve'], 
    "last": ["Stark", 'Rogers'], 
    "email": ["person010@example.com", 'person005@example.com']
}
df2=pd.DataFrame(people)

In [19]:
df2

   first    last               email
0   Tony   Stark  person010@example.com
1  Steve  Rogers      person005@example.com

In [20]:
df._append(df2,ignore_index=True)

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3       person010@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [21]:
df

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe

In [22]:
df=df._append(df2,ignore_index=True)

In [23]:
df

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3       person010@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [24]:
df.drop(index=4)

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3       person010@example.com            NaN   Tony    Stark

In [25]:
df

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
1        person014@example.com       Jane Doe   Jane      Doe
2        person015@example.com       John Doe   John      Doe
3       person010@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers

In [26]:
# df.drop(index=4,inplace=True)

In [27]:
filt = df['last']=='Doe'
df.drop(index=df[filt].index)

                     email      full_name  first     last
0  person007@example.com  Corey Schafer  Corey  Schafer
3       person010@example.com            NaN   Tony    Stark
4           person005@example.com            NaN  Steve   Rogers