# Sorting data

In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [5]:
df.sort_values(by='last')

   first     last                    email
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com
0  Corey  Schafer  person007@example.com

In [6]:
df.sort_values(by='last',ascending=False)

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [7]:
df.sort_values(by=['last','first'],ascending=False)

   first     last                    email
0  Corey  Schafer  person007@example.com
2   John      Doe        person015@example.com
1   Jane      Doe        person014@example.com

In [8]:
df.sort_values(by=['last','first'])

   first     last                    email
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com
0  Corey  Schafer  person007@example.com

In [9]:
people = {
    "first": ["Corey", 'Jane', 'John','Adam'], 
    "last": ["Schafer", 'Doe', 'Doe','Doe'], 
    "email": ["person007@example.com", 'person014@example.com', 'person015@example.com','person001@example.com']
}

In [10]:
df = pd.DataFrame(people)

In [11]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com
3   Adam      Doe              person001@example.com

In [12]:
df.sort_values(by=['last','first'],ascending=False)

   first     last                    email
0  Corey  Schafer  person007@example.com
2   John      Doe        person015@example.com
1   Jane      Doe        person014@example.com
3   Adam      Doe              person001@example.com

In [13]:
df.sort_values(by=['last','first'],ascending=[False,True])

   first     last                    email
0  Corey  Schafer  person007@example.com
3   Adam      Doe              person001@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [14]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com
3   Adam      Doe              person001@example.com

In [15]:
df.sort_values(by=['last','first'],ascending=[False,True],inplace=True)

In [16]:
df

   first     last                    email
0  Corey  Schafer  person007@example.com
3   Adam      Doe              person001@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com

In [17]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  person007@example.com
1   Jane      Doe        person014@example.com
2   John      Doe        person015@example.com
3   Adam      Doe              person001@example.com

In [18]:
df['last'].sort_values()

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: object