In [1]:
import pandas as pd
df=pd.read_csv("data/survey_results_public.csv",index_col='Respondent')
schema_df = pd.read_csv("data/survey_results_schema.csv",index_col='Column')
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [2]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
11         NaN
12         NaN
13     90000.0
14     57060.0
15         NaN
Name: ConvertedComp, dtype: float64

In [12]:
schema_df.loc['ConvertedComp','QuestionText']

'Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks.'

In [13]:
schema_df.sort_index(inplace=True)

In [14]:
schema_df

                                                             QuestionText
Column
Age                     What is your age (in years)? If you prefer not...
Age1stCode              At what age did you write your first line of c...
BetterLife              Do you think people born today will have a bet...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BlockchainOrg           How is your organization thinking about or imp...
CareerSat               Overall, how satisfied are you with your caree...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salar...
Containers              How do you use containers (Docker, Open Contai...
ConvertedComp           Salary converted to annual USD salaries using ...
Country                         In which country do you currently reside?
CurrencyDesc            Which currency do you use day-to-day? If your ...
CurrencySymbol          Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear  Which of the following database environments h...
DatabaseWorkedWith      Which of the following database environments h...
Dependents              Do you have any dependents (e.g., children, el...
DevEnviron              Which development environment(s) do you use re...
DevType                 Which of the following describe you? Please se...
EdLevel                 Which of the following best describes the high...
EduOther                Which of the following types of non-degree edu...
Employment              Which of the following best describes your cur...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Ethnicity               Which of the following do you identify as? Ple...
Extraversion              Do you prefer online chat or IRL conversations?
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Gender                  Which of the following do you currently identi...
Hobbyist                                          Do you code as a hobby?
ITperson                 Are you the "IT support person" for your family?
ImpSyn                  For the specific work you do, and the years of...
JobFactors              Imagine that you are deciding between two job ...
JobSat                  How satisfied are you with your current job? (...
JobSeek                 Which of the following best describes your cur...
LanguageDesireNextYear  Which of the following programming, scripting,...
LanguageWorkedWith      Which of the following programming, scripting,...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
MainBranch              Which of the following options best describes ...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
MiscTechWorkedWith      Which of the following other frameworks, libra...
OffOn                         Have you tried turning it off and on again?
OpSys                   What is the primary operating system in which ...
OpenSource              How do you feel about the quality of open sour...
OpenSourcer                   How often do you contribute to open source?
OrgSize                 Approximately how many people are employed by ...
PlatformDesireNextYear  Which of the following platforms have you done...
PlatformWorkedWith      Which of the following platforms have you done...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
Respondent              Randomized respondent ID number (not in order ...
ResumeUpdate            Think back to the last time you updated your r...
SOAccount                           Do you have a Stack Overflow account?
SOComm                  Do you consider yourself a member of the Stack...
SOFindAnswer            On average, how many times a week do you find ...
SOHowMuchTime           About how much time did you save? If you're no...
SOJobs                  Have you ever used or visited Stack Overflow J...
SONewContent            Would you like to see any of the following on ...
SOPartFreq              How frequently would you say you participate i...
SOTimeSaved             Think back to the last time you solved a codin...
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
ScreenName                                           What do you call it?
Sexuality               Which of the following do you currently identi...
SocialMedia                   What social media site do you use the most?
Student                 Are you currently enrolled in a formal, degree...
SurveyEase              How easy or difficult was this survey to compl...
SurveyLength            How do you feel about the length of the survey...
Trans                                     Do you identify as transgender?
UndergradMajor          What was your main or most important field of ...
UnitTests               Does your company regularly employ unit tests ...
WebFrameDesireNextYear  Which of the following web frameworks have you...
WebFrameWorkedWith      Which of the following web frameworks have you...
WelcomeChange           Compared to last year, how welcome do you feel...
WorkChallenge           Of these options, what are your greatest chall...
WorkLoc                                   Where would you prefer to work?
WorkPlan                          How structured or planned is your work?
WorkRemote                                How often do you work remotely?
WorkWeekHrs              On average, how many hours per week do you work?
YearsCode               Including any education, how many years have y...
YearsCodePro            How many years have you coded professionally (...

In [15]:
schema_df.loc[['CompTotal','ConvertedComp','WorkWeekHrs','CodeRevHrs','Age'],'QuestionText']

Column
CompTotal        What is your current total compensation (salar...
ConvertedComp    Salary converted to annual USD salaries using ...
WorkWeekHrs       On average, how many hours per week do you work?
CodeRevHrs       On average, how many hours per week do you spe...
Age              What is your age (in years)? If you prefer not...
Name: QuestionText, dtype: object

In [16]:
df[['CompTotal','ConvertedComp','WorkWeekHrs','CodeRevHrs','Age']].median()

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [17]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [18]:
df['ConvertedComp'].count()

55823

In [19]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [21]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [22]:
df['SocialMedia']

Respondent
1          Twitter
2        Instagram
3           Reddit
4           Reddit
5         Facebook
           ...
88377      YouTube
88601          NaN
88802          NaN
88816          NaN
88863     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [23]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: count, dtype: int64

In [24]:
df['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [25]:
df['Country'].value_counts()

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [26]:
df.groupby(['Country'])

In [28]:
country_grp=df.groupby(['Country'])

In [29]:
country_grp.get_group('Bangladesh')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
42,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,No,"Secondary school (e.g. American high school, G...",NaN,Taken a part-time in-person course in programm...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher;Data or business analyst;D...,8,15,5,Neither satisfied nor dissatisfied,Slightly satisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles,No,Office environment or company culture;Remote w...,I was preparing for a job search,USD,United States dollar,NaN,Monthly,NaN,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",10.0,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP;TypeScript,JavaScript;PHP;TypeScript,MySQL,Firebase;MySQL,WordPress,WordPress,jQuery;Laravel,jQuery;Laravel;React.js,Node.js,Node.js,Visual Studio Code,Windows,Development;Testing,Accepting Bitcoin or other coins and tokens as...,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,Facebook,Online,Screen Name,2008,Daily or almost daily,Find answers to specific questions;Meet other ...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Daily or almost daily,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,30.0,Man,No,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Easy
171,I am a student who is learning to code,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Bangladesh,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Participated in online coding competitions (e....,NaN,Academic researcher;Educator;Student,4,19,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Specific department or team I'd be working on;...,I heard about a job opportunity (from a recrui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;C#;HTML/CSS;Java;Objective-C;PH...,Bash/Shell/PowerShell;Clojure;JavaScript,MySQL;Oracle,SQLite,Android;iOS,NaN,ASP.NET,jQuery;Laravel;React.js;Vue.js,TensorFlow,.NET;Node.js;Unity 3D,NetBeans;Notepad++,Windows,I do not use containers,NaN,NaN,Yes,Yes,What?,Facebook,In real life (in person),Login,2018,A few times per week,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,Yes,"No, not at all",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
300,I am a student who is learning to code,No,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bangladesh,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Designer;Developer, back-end;Developer, front-...",2,18,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Specific department or team I'd be working on;...,I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;SQL,Dart;HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,Microsoft SQL Server;MySQL;SQLite,MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;Windows,Android;AWS;Google Cloud Platform;Heroku;Linux...,jQuery;Spring,Django;jQuery;Spring,Flutter;Node.js,Flutter;Node.js;TensorFlow,Android Studio;IntelliJ;NetBeans;PyCharm;Visua...,Windows,Development,NaN,NaN,Yes,Yes,What?,Facebook,In real life (in person),Username,2017,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers,NaN,Man,NaN,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
324,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Bangladesh,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,20 to 99 employees,"Developer, back-end;Developer, embedded applic...",15,17,11,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write code by hand (e.g., on a whiteboard);Sol...",No,Office environment or company culture;Opportun...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2500.0,Monthly,30000.0,45.0,There's no schedule or spec; I work on what se...,Lack of support from management;Not enough peo...,About half the time,Office,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Not sure,I have little or no influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,Microsoft SQL Server;Oracle,Microsoft SQL Server;Oracle,Android;Windows,Android;Windows,Angular/Angular.js;ASP.NET,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Cordova;.NET;Node.js,Cordova;.NET;.NET Core;Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,NaN,Not at all,NaN,No,Yes,Yes,Facebook,In real life (in person),UserID,2010,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,34.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
690,"I used to be a developer by profession, but no...",No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Retired,Bangladesh,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly,Assembly,NaN,NaN,Android;Other(s):,Android;Other(s):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40072,NaN,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",NaN,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scala,Scala,Couchbase,DynamoDB,NaN,NaN,NaN,NaN,NaN,NaN,Komodo,MacOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62740,NaN,No,Less than once per year,NaN,NaN,Bangladesh,No,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Other(s):,NaN,SQLite,Cassandra,Android,NaN,NaN,Laravel,.NET,NaN,Light Table,MacOS,I do not use containers,NaN,NaN,Yes,Yes,Yes,Facebook,Online,NaN,I don't remember,I have never visited Stack Overflow (before to...,Learn how to do things I didn’t necessarily lo...,Less than once per week,The other resource was much faster,60+ minutes,NaN,NaN,Yes,Yes,"Yes, somewhat",Just as welcome now as I felt last year,NaN,29.0,NaN,NaN,Bisexual,NaN,NaN,Too short,Easy
64910,NaN,No,Less than once a month but more than once per ...,NaN,NaN,Bangladesh,NaN,Associate degree,"A humanities discipline (ex. literature, histo...",NaN,NaN,NaN,6,34,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly,Other(s):,NaN,NaN,Android,NaN,NaN,Ansible,NaN,Visual Studio,Linux-based,"Outside of work, for personal projects",NaN,NaN,Yes,Yes,What?,Facebook,Online,NaN,NaN,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,Stack Overflow was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,NaN,NaN,NaN,No,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult
78004,NaN,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",NaN,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Useful across many domains and could change ma...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Contribute to a library of information,More than 10 times per week,The other resource was much faster,0-10 minutes,Yes,Multiple times per day,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN
81624,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Retired,Bangladesh,"Yes, full-time","Professional degree (JD, MD, etc.)","Information systems, information technology, o...",Participated in online coding competitions (e....,NaN,NaN,1,11,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly,Microsoft SQL Server;MySQL;Redis;SQLite,Firebase;Microsoft SQL Server;MySQL;SQLite,NaN,Android,Angular/Angular.js;ASP.NET,NaN,Chef;.NET;.NET Core;React Native;Unreal Engine...,NaN,Android Studio;Atom;IPython / Jupyter;NetBeans...,BSD,Development,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,Facebook,Online,Login,NaN,Daily or almost daily,Learn how to do things I didn’t necessarily lo...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,"No, I didn't know that Stack Overflow had a jo...",Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers,NaN,"Non-binary, genderqueer, or gender non-conforming",Yes,NaN,NaN,Yes,Appropriate in length,Easy

In [31]:
filt=(df['Country']=='United States')
df.loc[filt]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, full-stack",3,19,1,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,Opportunities for professional development;How...,I was preparing for a job search,USD,United States dollar,69000.0,Yearly,69000.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Non-work...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,Oracle;SQLite,Couchbase;DynamoDB;Elasticsearch;Firebase;Oracle,Docker;Google Cloud Platform,Docker;iOS;Slack,React.js;Ruby on Rails,Express;React.js;Ruby on Rails;Vue.js,NaN,React Native;TensorFlow,Visual Studio Code,MacOS,Development;Testing;Production,NaN,Useful for immutable record keeping outside of...,Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","10,000 or more employees","Designer;Developer, back-end;Developer, deskto...",12,8,8,Very satisfied,Very satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Remote work options;Diversity of the company o...,I was preparing for a job search,USD,United States dollar,114000.0,Yearly,114000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Far above average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,C#;HTML/CSS;JavaScript;Objective-C;Ruby;SQL;Sw...,Microsoft SQL Server;MySQL;Redis;SQLite,Microsoft SQL Server;MySQL;Redis;SQLite,AWS;Docker;Linux;MacOS;Microsoft Azure;Windows...,Android;Docker;iOS;Linux;MacOS;Microsoft Azure...,Angular/Angular.js;ASP.NET;Drupal;Express;jQue...,Angular/Angular.js;ASP.NET,.NET;.NET Core;Node.js;Xamarin,.NET;.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Xcode,MacOS,Development;Testing,Not at all,A passing fad,Yes,SIGH,Yes,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,NaN,34.0,Man,No,Gay or Lesbian,NaN,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78292,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",Completed an industry certification program (e...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher,42,14,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;Python,Bash/Shell/PowerShell;C;Python,SQLite,SQLite,Linux;Raspberry Pi;Other(s):,Linux;Raspberry Pi;Other(s):,NaN,NaN,Chef,NaN,Emacs;IPython / Jupyter,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),NaN,2013,A few times per week,Find answers to specific questions,Less than once per week,The other resource was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,NaN,60.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
82717,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Less than 1 year,NaN,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android;Windows,Android;Microsoft Azure;Windows,NaN,NaN,NaN,NaN,NaN,MacOS,Testing,NaN,NaN,No,SIGH,Yes,Facebook,In real life (in person),Username,2018,Less than once per month or monthly,Find answers to specific questions,Less than once per week,NaN,60+ minutes,No,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Not sure,NaN,Industry news about technologies you're intere...,44.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
83397,NaN,Yes,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,12,9,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python;SQL,C;C++;C#;Go;Java;JavaScript;Python;R;Ruby;SQL;...,NaN,NaN,Android;Arduino;Slack,Android;Arduino;Docker;iOS;Raspberry Pi;Slack,Flask,Django;Drupal;Flask;jQuery;React.js,NaN,Chef;Torch/PyTorch,Eclipse;IPython / Jupyter;Sublime Text,MacOS,I do not use containers,NaN,NaN,NaN,SIGH,Yes,NaN,NaN,Handle,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,NaN,27.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Designer;Marketing or sales professional,20,7,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Go;HTML/CSS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,NaN,In real life (in person),Handle,2008,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Developer, desktop or ente...",38,10,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,Bash/Shell/PowerShell;C;Go;HTML/CSS;JavaScript...,NaN,NaN,Linux,Linux;Raspberry Pi,React.js,Vue.js,Node.js,Ansible,Vim,Linux-based,I do not use containers,NaN,An irresponsible use of resources,No,NaN,Yes,I don't use social media,In real life (in person),Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [33]:
df.loc[filt]['SocialMedia'].value_counts()

SocialMedia
Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: count, dtype: int64

In [34]:
country_grp['SocialMedia'].value_counts()

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
                                         ..
Zimbabwe     Facebook                     3
             YouTube                      3
             LinkedIn                     2
             Instagram                    2
             Reddit                       1
Name: count, Length: 1220, dtype: int64

In [39]:
df.loc[filt][['SocialMedia','Country']]

                         SocialMedia        Country
Respondent
4                             Reddit  United States
13                           Twitter  United States
22                         Instagram  United States
23                            Reddit  United States
26          I don't use social media  United States
...                              ...            ...
78292       I don't use social media  United States
82717                       Facebook  United States
83397                            NaN  United States
85642                            NaN  United States
88282       I don't use social media  United States

[20949 rows x 2 columns]

In [40]:
country_grp['SocialMedia'].value_counts().loc['China']

SocialMedia
WeChat 微信                   403
YouTube                      53
Weibo 新浪微博                   42
Twitter                      27
I don't use social media     27
Reddit                       12
LinkedIn                     11
Facebook                      8
Instagram                     7
Youku Tudou 优酷                7
WhatsApp                      3
VK ВКонта́кте                 1
Name: count, dtype: int64

In [41]:
df.rename(columns={'ConvertedComp':'Salary'},inplace=True)

In [43]:
country_grp['Salary'].median().loc['Germany']

63016.0

In [44]:
country_grp['Salary'].agg(['median','mean']).loc['Germany']

median     63016.000000
mean      109256.884066
Name: Germany, dtype: float64

In [46]:
country_grp['Salary'].agg(['median','mean']).head(50)

                                         median           mean
Country
Afghanistan                              6222.0  101953.333333
Albania                                 10818.0   21833.700000
Algeria                                  7878.0   34924.047619
Andorra                                160931.0  160931.000000
Angola                                   7764.0    7764.000000
Antigua and Barbuda                         NaN            NaN
Argentina                               17760.0   29467.265306
Armenia                                 19692.0   24691.733333
Australia                               79783.0  171541.116279
Austria                                 51559.0   83955.639604
Azerbaijan                              15858.0   15785.750000
Bahamas                                     NaN            NaN
Bahrain                                 15912.0   23934.000000
Bangladesh                               8764.0   21249.652000
Barbados                                21000.0   21000.000000
Belarus                                 24000.0   29442.330645
Belgium                                 48120.0   73185.564655
Belize                                      NaN            NaN
Benin                                       NaN            NaN
Bhutan                                      NaN            NaN
Bolivia                                 13020.0   17977.360000
Bosnia and Herzegovina                  18360.0   24996.283333
Botswana                                38410.0   40994.000000
Brazil                                  18036.0   32623.570000
Brunei Darussalam                        6096.0    6096.000000
Bulgaria                                28080.0   42642.419355
Burkina Faso                             8388.0    8388.000000
Burundi                                  3606.0    3606.000000
Cambodia                                10420.0   31957.000000
Cameroon                                 6288.0   24194.913043
Canada                                  68705.0  134018.564909
Cape Verde                                  NaN            NaN
Chad                                     6288.0    6288.000000
Chile                                   27528.0   40438.909722
China                                   28464.0   57430.421053
Colombia                                15528.0   24502.876190
Congo, Republic of the...               18000.0   16852.000000
Costa Rica                              38400.0   40982.647059
Croatia                                 24108.0   45305.660714
Cuba                                     3666.0   10920.555556
Cyprus                                  38496.0   55789.297297
Czech Republic                          35637.0   42486.641822
Côte d'Ivoire                           12576.0   11579.076923
Democratic People's Republic of Korea   32880.0   32880.000000
Democratic Republic of the Congo       110484.0  110484.000000
Denmark                                 82860.0  113769.554762
Djibouti                                18876.0   18876.000000
Dominica                                    NaN            NaN
Dominican Republic                      16667.0   27355.147059
Ecuador                                 21800.0   26596.107143

In [48]:
country_respondents=df['Country'].value_counts()
country_respondents

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [50]:
country_uses_python=country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [51]:
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [54]:
python_df=pd.concat([country_respondents,country_uses_python],axis='columns')

In [55]:
python_df

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [56]:
python_df.rename(columns={'count':'NumRespondents','LanguageWorkedWith':'NumKnowsPython'},inplace=True)

In [58]:
python_df

                   NumRespondents  NumKnowsPython
Country
United States               20949           10083
India                        9061            3105
Germany                      5866            2451
United Kingdom               5737            2384
Canada                       3395            1558
...                           ...             ...
Tonga                           1               0
Timor-Leste                     1               1
North Korea                     1               0
Brunei Darussalam               1               0
Chad                            1               0

[179 rows x 2 columns]

In [59]:
python_df['PctknowsPython'] =(python_df['NumKnowsPython']/python_df['NumRespondents'])*100

In [60]:
python_df

                   NumRespondents  NumKnowsPython  PctknowsPython
Country
United States               20949           10083       48.131176
India                        9061            3105       34.267741
Germany                      5866            2451       41.783157
United Kingdom               5737            2384       41.554820
Canada                       3395            1558       45.891016
...                           ...             ...             ...
Tonga                           1               0        0.000000
Timor-Leste                     1               1      100.000000
North Korea                     1               0        0.000000
Brunei Darussalam               1               0        0.000000
Chad                            1               0        0.000000

[179 rows x 3 columns]

In [62]:
python_df.loc['Bangladesh']

NumRespondents    605.000000
NumKnowsPython    204.000000
PctknowsPython     33.719008
Name: Bangladesh, dtype: float64

In [67]:
df['YearsCode']

Respondent
1          4
2        NaN
3          3
4          3
5         16
        ...
88377    NaN
88601    NaN
88802    NaN
88816    NaN
88863      8
Name: YearsCode, Length: 88883, dtype: object

In [68]:
df['YearsCode'] = pd.to_numeric(df['YearsCode'].replace({'Less than 1 year': '0', 'More than 50 years': '51'}), errors='coerce')

In [70]:
df['YearsCode'].unique()

In [71]:
df['YearsCode'].replace('Less than 1 year',0,inplace=True)
df['YearsCode'].replace('More than 50 years',0,inplace=True)

In [72]:
df['YearsCode'].unique()

In [74]:
df['YearsCode'] = pd.to_numeric(df['YearsCode'].replace({'Less than 1 year': '0', 'More than 50 years': '51'}), errors='coerce')

In [75]:
df['YearsCode'].mean()

In [76]:
df['YearsCode'].median()